sonar.host.url=${env.SONAR_HOST_URL}
sonar.token=${env.SONAR_TOKEN}
sonar.sourceEncoding=UTF-8
sonar.projectKey=smartlingua-monorepo
sonar.projectName=SmartLingua Monorepo
sonar.qualitygate.wait=true

sonar.sources=backend,frontend/smartlingua-ui/src
sonar.tests=backend,frontend/smartlingua-ui/src
sonar.test.inclusions=**/*.spec.ts,**/*Test.java,**/*Tests.java
sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/.idea/**
sonar.coverage.jacoco.xmlReportPaths=backend/**/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=frontend/smartlingua-ui/coverage/**/lcov.info
sonar.java.binaries=backend/**/target/classes
